language: python
python:
#  - "2.6"
  - "2.7"
#  - "3.2"
#  - "3.3"
#  - "3.4"
  - "3.5"
#  - "pypy"
# command to install dependencies
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
# command to run tests
#before_script:
#    - pylint src/fb_messenger
script:
  - nosetests src/fb_messenger/test
#after_success:
#  coveralls